version: "2"
services:
  redis:
    image: redis
    container_name: watch-lb-redis
    restart: always
    entrypoint: redis-server
    command: ["--appendonly", "yes"]
    volumes:
      - ./redis-docker-data:/data
  watch-lb:
    restart: always
    container_name: watch-lb
    image: "dscheirer/watch-lb"
    env_file:
      - .env-docker
    depends_on:
      - "redis"
    build:
      context: ./
